### ISSUE TITLE
update to be able to merge it with new SDK?

### ISSUE THREAD

**Issue by j2l** [Naxela/PPM#4]
Thanks Alexander!

I compared one of the file from 0.3 with SDK 2020.2 and it's hard to tell what is 2019-08 to 2020-02 changes and what is needed for PPM.
Multiplying this with all the files, I just didn't continue.
PPM is very interesting though. Or is there something I missed in the newest Armory releases?

**Comment by Naxela** [comment]
Hi,

There's been some breaking changes from 2019-08 till now, but I'm planning on updating PPM to the latest version once I've some time on my hand, which is hopefully soon

**Comment by j2l** [comment]
Oh, great!
Thanks!

**Comment by divineniiquaye** [comment]
`I'm planning on updating PPM to the latest version once I've some time on my hand, which is hopefully soon` = Yeppi am waiting

**Comment by Naxela** [comment]
Should be updated to the latest version now

**Comment by j2l** [comment]
Woot woot, this is cool! thanks! I'll try ASAP

**Comment by luboslenco** [comment]
@Naxela might be a good time to merge into armory now, since it's freshly updated? Would you mind opening PR? Looks awesome!

**Comment by Naxela** [comment]
@luboslenco 
Hi Lubos,

Thanks - I'll revision the addon a bit before doing a pull-request, instead of PPM I'll just rename it to postprocess (realtime postprocess?), this will probably be less confusing for users too in terms of nodes, etc.

I'm a little in doubt of the best ways of pushing a large amount of uniforms, especially in terms of performance. Currently, I'm rewriting the uniforms to Vec3 as it was the only type I managed to push into the uniforms without error, although an array of floats (such as Float32Array perhaps?) would be more suitable, but I've no idea how to make that work.

- In any case, I'll make a PR soon along with some minor commit description/docs
